name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: Ruby ${{matrix.ruby}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.experimental}}

    services:
      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    strategy:
      matrix:
        os:
          - ubuntu

        ruby:
          - "3.2"
          - "3.3"
          - "3.4"

        experimental: [false]

        include:
          - os: ubuntu
            ruby: head
            experimental: true

    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true

    - name: Run tests
      timeout-minutes: 10
      env:
        REDIS_URL: redis://127.0.0.1:6379/0
      run: bundle exec sus
